export const toDresses = () => "/dresses";
export const toPants = () => "/pants";
export const toBlouses = () => "/blouses";
export const toShoes = () => "/shoes";
export const toMainPage = () => "/mainPage";
export const toProductsDetails = () => "/dresses/:id";
export const toLogin = () => "/login";
export const toCreateAccount = () => "/createAccount";
export const toShopRules = () => "/shopRules"
